image: hudecof/ansible-tests:latest

before_script:
 - pip install -U setuptools pip
 - pip install wheel
 - pip install ansible
 - pip install docker-py
 - pip install molecule
 - pip install -U ansible-lint

test:
  script:
    - cd ../ && rm -rf hudecof.box-info &&  mv box-info hudecof.box-info && cd hudecof.box-info
    - molecule --debug test
    - cd ../ && mv  hudecof.box-info box-info && cd box-info
