image: hudecof/ansible-tests:latest

before_script:
 - pip install -U setuptools pip
 - pip install wheel
 - pip install ansible
 - pip install docker-py
 - pip install molecule

test:
  script:
    - molecule test
